name: endel_clone
publish_to: 'none'
description: Generative soundscapes (Flutter + Rust FFI)
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ffi: ^2.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # Include the presets directory once; Flutter will recursively include JSON files.
    - assets/presets/
